#server:
#  port: 8080

spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888/

#message: Hello Frank catalog-service

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'